language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - sudo freshclam --verbose
  - sudo service clamav-daemon start
  - pip install .
script:  python setup.py nosetests
matrix:
  allow_failures:
    - python: "2.5"
